### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by vietly23** [waynebhayes/SANA#1]
Should we make a style guide for everyone to follow, and should it be in the README? I want to start contributing, but I'd rather avoid introducing different styles or mixing tabs and spaces in the code.

**Comment by khosravipasha** [comment]
Sounds great, we can either add it as section in the README file, or a separate file called "contribution".

After we finish the refactoring we should also write a more comprehensive README file with examples and guides for the end-user.

**Comment by red4711** [comment]
Google has an established style guide that is widely used. They also
provided a cppchecker in order to check to compliance so it would be a good
idea to use that.

**Comment by vietly23** [comment]
Great. I'll just add that to the README then under Contribution,
